# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# network_analysis_jc_ks.py
# Created on: 2017-05-09 09:02:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: network_analysis_jc_ks <Input_Stop_Locations> <Filter_Stop_Locations> <Choose_Route_Network_Dataset> <Impedance_Attribute> <Restrictions> <Accumulators> <Output_Path_Shape> <U_Turn_Policy> <Use_Hierarchy_in_Analysis> <Field_Mappings> <Sort_Field> <Group_By_Fields> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

project_dir = "C:/temp/RegionalTransitDatabase/"

#layer paths
Stop_Locations = project_dir + "data/network_analyst.gdb/Route_Pattern_Bus_Stops"

#network data set must be loaded into an MXD Table of contents from catalog. 
# see https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/16 for more
Network_Dataset = project_dir + "/data/TomTom_2015_12_NW.gdb/Routing/Routing_ND"

#arguments
Filter_Stop_Locations = "Route_ID ='1'"
Restrictions = "'Avoid Walkways';'Driving a Public Bus'"
Group_By_Fields = "Agency_Route_ID" 
Sort_Field = "stop_sequence"
Field_Mappings = "Name Agency_Route_ID #;RouteName Agency_Route_ID #"
Impedance_Attribute = "Miles" # provide a default value if unspecified
Restrictions = "'Avoid Walkways';'Driving a Public Bus'" # provide a default value if unspecified
Accumulators = "Miles;Minutes" # provide a default value if unspecified
Output_Path_Shape = "TRUE_LINES_WITHOUT_MEASURES" # provide a default value if unspecified
U_Turn_Policy = "ALLOW_UTURNS" # provide a default value if unspecified
Use_Hierarchy_in_Analysis = "true" # provide a default value if unspecified
Network_Analyst_Layer = "R1"
Solve_Succeeded = "false"
Child_Data_Element = "Routes"
HHTS_Trips__2_ = Network_Analyst_Layer
HHTS_Trips = "\\\\Mac\\Home\\Documents\\Planning\\DataManagement\\DataManagement.gdb\\utm\\HHTS_Trips"

arcpy.MakeFeatureLayer_management(in_features=Stop_Locations, 
    out_layer="temp_stops", 
    where_clause=Filter_Stop_Locations, 
    workspace="")

# Process: Iterate Feature Selection
# arcpy.IterateFeatureSelection_mb(Output_Layer, Group_By_Fields, "false")

# Replace a layer/table view name with a path to a dataset (which can be a layer file) or create the layer/table view within the script
# The following inputs are layers or table views: "Routing_ND"

# Process: Make Route Layer
arcpy.MakeRouteLayer_na(Network_Dataset, Network_Analyst_Layer, 
                        Impedance_Attribute, "USE_INPUT_ORDER", "PRESERVE_BOTH", 
                        "NO_TIMEWINDOWS", Accumulators, U_Turn_Policy, 
                        Restrictions, Use_Hierarchy_in_Analysis, "", Output_Path_Shape, "")

# Process: Add Locations
arcpy.AddLocations_na(in_network_analysis_layer=Network_Analyst_Layer,
                         sub_layer="Stops",
                         in_table="temp_stops",
                         field_mappings=Field_Mappings,
                         search_tolerance="5000 Meters",
                         sort_field=Sort_Field,
                         search_criteria="Streets SHAPE;Routing_ND_Junctions NONE",
                         match_type="MATCH_TO_CLOSEST",
                         append="APPEND",
                         snap_to_position_along_network="NO_SNAP",
                         snap_offset="5 Meters",
                         exclude_restricted_elements="INCLUDE",
                         search_query="Streets #;Routing_ND_Junctions #")

# Replace a layer/table view name with a path to a dataset (which can be a layer file) or create the layer/table view within the script
# The following inputs are layers or table views: "R1"

# Process: Solve
arcpy.Solve_na(Network_Analyst_Layer, "SKIP", "TERMINATE", "")

# # Process: Select Data
# arcpy.SelectData_management(Network_Analyst_Layer, Child_Data_Element)

# # Process: Append
# arcpy.Append_management("Route\\Routes", HHTS_Trips, "NO_TEST", "", "")

