# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# network_analysis_jc_ks.py
# Created on: 2017-05-09 09:02:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: network_analysis_jc_ks <Input_Stop_Locations> <Filter_Stop_Locations> <Choose_Route_Network_Dataset> <Impedance_Attribute> <Restrictions> <Accumulators> <Output_Path_Shape> <U_Turn_Policy> <Use_Hierarchy_in_Analysis> <Field_Mappings> <Sort_Field> <Group_By_Fields> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.overwriteOutput = True

PROJECT_DIR = "C:/temp/RegionalTransitDatabase/"

ntwrk_path = PROJECT_DIR + "data/TomTom_2015_12_NW.gdb/Routing/Routing_ND"

#network args
ntwrk_args = {"network_dataset":ntwrk_path,
"impedance_attribute":"miles",
"u_turn_policy":"allow_uturns",
"restrictions":"'avoid walkways';'driving a public bus'", 
"accumulators":"miles;minutes", 
"output_path_shape":"true_lines_without_measures", 
"use_hierarchy_in_analysis":"true"}

def load_network(ntwrk_name, **kwargs):
    print(kwargs["network_dataset"])
    arcpy.MakeRouteLayer_na(kwargs["network_dataset"], ntwrk_name, 
        kwargs["impedance_attribute"], "use_input_order", "preserve_both", 
        "no_timewindows", kwargs["accumulators"], kwargs["u_turn_policy"], 
        kwargs["restrictions"], kwargs["use_hierarchy_in_analysis"], "", kwargs["output_path_shape"], "")
    return ntwrk_name

load_network("N1",**ntwrk_args)


#stop arguments
stop_args = {"restrictions" : "'avoid walkways';'driving a public bus'",
            "group_by_fields" : "agency_route_id", 
            "sort_field" : "stop_sequence",
            "field_mappings": "name agency_route_id #;routename agency_route_id #",
            "solve_succeeded" : "false",
            "child_data_element" : "routes",
            #hhts_trips__2_ = network_analyst_layer,
            "hhts_trips" : "empty_fc",
            "stop_locations" : PROJECT_DIR + "data/network_analyst.gdb/route_pattern_bus_stops"}

def load_stops(ntwrk_name,mtcgis_agency_route_pattern,**kwargs):
    #mtcgis_agency_route_pattern_id is a legacy id that mtc uses to uniquely identify routes and stops
    import re
    route_shortname = re.sub("\W","", mtcgis_agency_route_pattern)
    route_filter = "Agency_Route_Pattern =" + mtcgis_agency_route_pattern
    arcpy.MakeFeatureLayer_management(in_features=kwargs["stop_locations"], 
        out_layer=route_shortname, 
        where_clause=route_filter, 
        workspace="")
    arcpy.na.AddLocations(in_network_analysis_layer=ntwrk_name,
                     sub_layer="Stops",
                     in_table=route_shortname,
                     field_mappings=kwargs["field_mappings"],
                     search_tolerance="5000 Meters",
                     sort_field=kwargs["sort_field"],
                     search_criteria="Streets SHAPE;Routing_ND_Junctions NONE",
                     match_type="MATCH_TO_CLOSEST",
                     append="APPEND",
                     snap_to_position_along_network="NO_SNAP",
                     snap_offset="5 Meters",
                     exclude_restricted_elements="INCLUDE",
                     search_query="Streets #;Routing_ND_Junctions #")
    return route_shortname

route_name = "'AC - 1 - Inbound'"
network_name = "N1"
load_network(network_name,**ntwrk_args)
load_stops(network_name, route_name, **stop_args)

arcpy.Solve_na(network_name, "SKIP", "TERMINATE", "")
